_target_: robots.airbots.airbot_play.airbot_play_2_demonstration.AIRBOTPlayDemonstration

# TODO: use demonstration groups, each of which has only one leader and multiple followers
# e.g. {group1:{leader:1, followers:[2,3]}, group2:{leader:4, followers:[5,6]}}
groups:
  g1:
    leader:
      _target_: robots.airbots.airbot_play.airbot_play_2.AIRBOTPlayConfig
      can_bus: "can0"
      eef_mode: "teacherv2"
    followers:
      - _target_: robots.airbots.airbot_play.airbot_play_2.AIRBOTPlayConfig
        can_bus: "can1"
        eef_mode: "teacherv2"
      # - _target_: robots.airbots.airbot_play.airbot_play_2.AIRBOTPlayConfig
      #   can_bus: "can2"
      #   eef_mode: "teacherv2"

# Troubleshooting: If one of your opencv cameras freeze during
# data recording due to bandwidth limit, you might need to plug the camera
# on another USB hub or PCIe card.
cameras:
  cam1:
    _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  # cam2:
  #   _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 2
  #   fps: 30
  #   width: 640
  #   height: 480
  # cam3:
  #   _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 4
  #   fps: 30
  #   width: 640
  #   height: 480
