_target_: robots.airbots.airbot_play.airbot_play_3_le.AIRBOTPlay

# Troubleshooting: If one of your opencv cameras freeze during
# data recording due to bandwidth limit, you might need to plug the camera
# on another USB hub or PCIe card.
cameras:
  cam1:
    _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  cam2:
    _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480
  cam2:
    _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 4
    fps: 30
    width: 640
    height: 480
