_target_: robots.airbots.scripts.airbot_play.AIRBOTPlay

robot_type: null

# Troubleshooting: If one of your opencv cameras freeze during
# data recording due to bandwidth limit, you might need to plug the camera
# on another USB hub or PCIe card.
cameras:
  cam1:
    _target_: le_studio.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480
