stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: none
  HTTP_PROXY: ${PROXY_URL}
  http_proxy: ${PROXY_URL}
  HTTPS_PROXY: ${PROXY_URL}
  https_proxy: ${PROXY_URL}
  ALL_PROXY: ${PROXY_URL}
  all_proxy: ${PROXY_URL}
  NO_PROXY: ${NO_PROXY_URL}
  no_proxy: ${NO_PROXY_URL}

style-test:
  stage: test
  tags:
    - linux/amd64
  image: registry.qiuzhi.tech/library/pre-commit:1.0
  variables:
    PIP_INDEX_URL: "https://mirrors.aliyun.com/pypi/simple"
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  cache:
    key: pre-commit
    paths:
      - .cache/pre-commit
  before_script:
    - pre-commit install
  script:
    - pre-commit run --all-files
