left:
  _target_: airbot_data_collection.airbot.robots.airbot_play_mock.AIRBOTPlay
  port: 50051
right:
  _target_: airbot_data_collection.airbot.robots.airbot_play_mock.AIRBOTPlay
  port: 50053

cameras:
  env_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.mock.MockCamera
    camera_index: 2
  left_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.mock.MockCamera
    camera_index: 4
  right_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.mock.MockCamera
    camera_index: 6
