/:
  _target_: airbot_ie.robots.airbot_play.AIRBOTPlay
  port: 50051
  observation:
    - interfaces:
        - joint_position
        - joint_velocity
        - joint_effort
        - pose

cameras:
  env_camera:
    _target_: airdc.common.devices.cameras.v4l2.V4L2Camera
    camera_index: 2
  # follow_camera:
  #   _target_: airdc.common.devices.cameras.v4l2.V4L2Camera
  #   camera_index: 4
