left:
  _target_: airbot_data_collection.airbot.robots.airbot_play.AIRBOTPlay
  port: 50051
right:
  _target_: airbot_data_collection.airbot.robots.airbot_play.AIRBOTPlay
  port: 50053

cameras:
  env_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.v4l2.BsonV4L2Camera
    camera_index: 2
    width: 640
    height: 480
  left_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.v4l2.BsonV4L2Camera
    camera_index: 4
    width: 640
    height: 480
  right_camera:
    _target_: airbot_data_collection.airbot.sensors.cameras.v4l2.BsonV4L2Camera
    camera_index: 6
    width: 640
    height: 480
