_target_: robots.airbots.airbot_tok.airbot_tok_2.AIRBOTTOK

arms_cfg:
  left:
    _target_: robots.airbots.airbot_play.airbot_play_2.AIRBOTPlayConfig
    can_bus: "can0"
    eef_mode: "gripper"
    default_action: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  right:
    _target_: robots.airbots.airbot_play.airbot_play_2.AIRBOTPlayConfig
    can_bus: "can1"
    eef_mode: "gripper"
    default_action: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

cameras:
  cam1:
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
    color_mode: "bgr"

data_style: 2.0  # 2.0 for data converted by convert_episodes.py