_target_: robots.airbots.airbot_tok.airbot_tok.AIRBOTTOK

arms_cfg:
  left:
    _target_: robots.airbots.airbot_play.airbot_play_3.AIRBOTPlayConfig
    arm_type: "play_long"
    end_effector: "G2"
    can_interface: "can0"
    domain_id: 100
    start_arm_joint_position:
      [
        -0.05664911866188049,
        -0.26874953508377075,
        0.5613412857055664,
        1.483367681503296,
        -1.1999313831329346,
        -1.3498512506484985,
      ]
    start_eef_joint_position: 0.0
    default_robot_mode: "ONLINE_IDLE"

  right:
    _target_: robots.airbots.airbot_play.airbot_play_3.AIRBOTPlayConfig
    arm_type: "play_long"
    end_effector: "G2"
    can_interface: "can1"
    domain_id: 88
    start_arm_joint_position:
      [
        -0.05664911866188049,
        -0.26874953508377075,
        0.5613412857055664,
        1.483367681503296,
        -1.1999313831329346,
        -1.3498512506484985,
      ]
    start_eef_joint_position: 0.0
    default_robot_mode: "ONLINE_IDLE"

cameras:
  cam1:
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
    color_mode: "bgr"
  # cam2:
  #   _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 2
  #   fps: 30
  #   width: 640
  #   height: 480
  # cam3:
  #   _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 4
  #   fps: 30
  #   width: 640
  #   height: 480
