_target_: robots.airbots.airbot_mmk.airbot_com_mmk2_bson.AIRBOTMMK2

ip: "localhost"

# NOTE: If you want to change the order of each part, be careful to change the order of each observation and action in the data conversion script simultaneously
components: ["left_arm", "left_arm_eef", "right_arm", "right_arm_eef"]

cameras:
  # head_camera: ["color"]
  left_camera: ["color"]
  right_camera: ["color"]
