_target_: robots.airbots.airbot_play.airbot_play_3.AIRBOTPlay

arm_type: "play_long"
end_effector: "G2"
can_interface: "can0"
domain_id: 100
start_arm_joint_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
start_eef_joint_position: 0.0
# ONLINE_TRAJ, ONLINE_IDLE, ONLINE_SERVO, DEMONSTRATE_PREP
default_robot_mode: "ONLINE_IDLE"

cameras:
  cam1:
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
    color_mode: "bgr"
  # cam2:
  #   _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 2
  #   fps: 30
  #   width: 640
  #   height: 480
  #   color_mode: "bgr"
  # cam3:
  #   _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 4
  #   fps: 30
  #   width: 640
  #   height: 480
  #   color_mode: "bgr"