_target_: robots.airbots.airbot_play.airbot_play_4.AIRBOTPlay

port: 50000
start_arm_joint_position:
  [
    0.5540932416915894,
    -0.47856107354164124,
    0.6315327882766724,
    1.3040741682052612,
    -0.8699550032615662,
    -1.335736632347107,
  ]
start_eef_joint_position: 1.0
# ONLINE_TRAJ, ONLINE_IDLE, ONLINE_SERVO, DEMONSTRATE_PREP
default_robot_mode: "ONLINE_IDLE"

cameras:
  "0":
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
    color_mode: "bgr"
  "1":
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 25
    width: 640
    height: 480
    color_mode: "bgr"
