_target_: robots.airbots.airbot_play.airbot_play_4.AIRBOTPlay

start_arm_joint_position: [-0.0711451917886734, -0.5575265288352966, 0.812352180480957, 1.503204345703125, -1.2754634618759155, -1.5604257583618164]
start_eef_joint_position: 0.0
# ONLINE_TRAJ, ONLINE_IDLE, ONLINE_SERVO, DEMONSTRATE_PREP
default_robot_mode: "ONLINE_IDLE"

cameras:
  "0":
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  "1":
    _target_: habitats.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480