_target_: robots.airbots.airbot_mmk.airbot_mmk2.AIRBOTMMK2

ip: "192.168.11.200"

default_action: null

cameras:
  head_camera: ["color"]
  # left_camera: ["color"]
  # right_camera: ["color"]

demonstrate: true
