_target_: robots.airbots.airbot_mmk.airbot_mmk2.AIRBOTMMK2

ip: "192.168.11.200"

default_action: null

cameras:
  # left_camera: "rgb"
  # right_camera: "rgb"
  head_camera: "rgb"

demonstrate: true
