_target_: robots.airbots.airbot_mmk.airbot_com_mmk2_bson.AIRBOTMMK2

ip: "192.168.40.128"

components: ["left_arm", "left_arm_eef", "right_arm", "right_arm_eef", "head", "spine"]
# components: ["left_arm", "left_arm_eef", "right_arm", "right_arm_eef"]

cameras:
  head_camera: "rgb"
  left_camera: "rgb"
  right_camera: "rgb"

demonstrate: true

default_action:
  [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -1.0,
    0.15,
  ]
