_target_: robots.airbots.airbot_mmk.airbot_mmk2.AIRBOTMMK2

ip: "192.168.40.19"

default_action:
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

cameras:
  # left_camera: "rgb"
  # right_camera: "rgb"
  head_camera: "rgb"
