_target_: robots.airbots.airbot_mmk.airbot_mmk2_bson.AIRBOTMMK2

ip: "192.168.11.200"

default_action: null

components: ["left_arm", "left_eef", "right_arm", "right_eef", "spine", "head"]
# components: ["left_arm", "left_eef", "right_arm", "right_eef"]

cameras:
  head_camera: "rgb"
  # left_camera: "rgb"
  # right_camera: "rgb"

demonstrate: false
